### ISSUE TITLE
working search bar (backend)

### ISSUE THREAD

**Issue by meghanakillada** [noyah81/p2ducks#16]
### Working Search Bar Feature

- backend for search bar using database
- links to the webpages if you type (ex. "sign in" OR "tweet")
- frontend for search results using html (will revamp in the future)
- may add more linked pages (like the minilab)

**Code Evidence:**
[backend for search database](https://github.com/noyah81/p2ducks/commit/b825b599d3ed115f9def047d1b5b63c3f4bdc9f9#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959)
[frontend for search bar](https://github.com/noyah81/p2ducks/commit/b825b599d3ed115f9def047d1b5b63c3f4bdc9f9#diff-3d7876948ea8a906bc68ab40268793750114caa2f639df2e15419937e91b8065)
[frontend for search results page](https://github.com/noyah81/p2ducks/commit/b825b599d3ed115f9def047d1b5b63c3f4bdc9f9#diff-237cfe0c2f1d295e0c024b411f64c86e82fb97e2f03753be929d4dd8bf6b762b)

**Runtime:**
[runtime](http://72.199.26.118:8080/)

**Comment by noyah81** [comment]
This was very creative. I was wondering how you created the search system. The code looks very thorough and I like how you utilized a database.

**Comment by sarahwxie** [comment]
Hi Maggie, this is really cool and I like how you integrated the database into it. I think the way you did the database is really great because it lets us see the different columns of the table.

**Comment by nivupai** [comment]
Great work Maggie! Making it so the user could find their profile or log-in button multiple different ways is very client oriented.

**Comment by AkhileshLG** [comment]
Good job on completing and organizing the ticket. I like how you had a general plan and bullet-pointed what other plans you had left. You also put all the code related to the project and inserted the runtime. You could in the future put plans for future ideas or improvements if you want to.
