### ISSUE TITLE
social media buttons (html page)

### ISSUE THREAD

**Issue by noyah81** [noyah81/p2ducks#45]
- a page for buttons that lead to other social media sites
- customized buttons lead to social media platforms
- Youtube, Linkedin, Facebook, Twitter
- ["Share on other platforms!" page](https://github.com/noyah81/p2ducks/blob/main/templates/share.html)

**Comment by meghanakillada** [comment]
This is a good ticket, it has a well organized layout for the ticket because of the organized bulleted list. Maybe add runtime links and code links too. This was a nice technical achievement, maybe talk about what other features you can add to the page.

**Comment by AkhileshLG** [comment]
This ticket is very direct and to the point. You covered the main topic in the title and have all the details. Maybe add a runtime link and ideas for the future.

**Comment by sarahwxie** [comment]
Hi Noya, the social media sharing feature looks really clean and nice on the finished site. I like how it includes Linkedin and Pinterest, since those are often ignored.

**Comment by nivupai** [comment]
Good job Noya. Since Hawkers is a social media page, including outlets and buttons to other forms of social media is a great way to stick to the basics and enhance our site.
